openapi: 3.0.0
info:
  title: "Game Logic Gateway API"
  description: "클라이언트와 C++ 서버 간의 중계를 위한 Node.js REST API 명세서"
  version: "1.0.0"

servers:
  - url: http://localhost:3000
    description: "로컬 개발 환경"

paths:
  # 1. 상태 체크 API (조회용이므로 기존 GET 방식 유지)
  /api/check/{id}:
    get:
      summary: "특정 세션/유저 상태 확인"
      tags:
        - System
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "조회 성공"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'

  # 2. 로그인 API (requestBody를 사용하는 POST 방식)
  /api/login:
    post:
      summary: "로그인 요청"
      tags:
        - Auth
      description: "본문(Body)에 포함된 ID 정보를 바탕으로 로그인을 시도합니다."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: "로그인 성공"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
        '400':
          description: "잘못된 요청 본문"
        '401':
          description: "인증 실패"

components:
  schemas:
    # [추가] 로그인 요청 시 보낼 데이터 구조
    LoginRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: "유저 식별자"
          example: "User_01"

    CommonResponse:
      type: object
      required: [success, code]
      properties:
        success:
          type: boolean
          example: true
        code:
          type: integer
          example: 200
        data:
          type: object
          nullable: true
          properties:
            receivedId:
              type: string
              example: "User_01"
            cppStatus:
              type: string
              example: "LOGGED_IN"
        error:
          $ref: '#/components/schemas/ErrorDetail'
          
    ErrorDetail:
      type: object
      nullable: true
      properties:
        message: { type: string, example: "Invalid request" }
        code: { type: string, example: "ERR_BAD_REQUEST" }