// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IPCProtocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_IPCProtocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_IPCProtocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_IPCProtocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_IPCProtocol_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_IPCProtocol_2eproto;
namespace IPC_Protocol {
class SWelcome;
struct SWelcomeDefaultTypeInternal;
extern SWelcomeDefaultTypeInternal _SWelcome_default_instance_;
}  // namespace IPC_Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::IPC_Protocol::SWelcome* Arena::CreateMaybeMessage<::IPC_Protocol::SWelcome>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace IPC_Protocol {

// ===================================================================

class SWelcome final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:IPC_Protocol.SWelcome) */ {
 public:
  inline SWelcome() : SWelcome(nullptr) {}
  ~SWelcome() override;
  explicit PROTOBUF_CONSTEXPR SWelcome(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SWelcome(const SWelcome& from);
  SWelcome(SWelcome&& from) noexcept
    : SWelcome() {
    *this = ::std::move(from);
  }

  inline SWelcome& operator=(const SWelcome& from) {
    CopyFrom(from);
    return *this;
  }
  inline SWelcome& operator=(SWelcome&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SWelcome& default_instance() {
    return *internal_default_instance();
  }
  static inline const SWelcome* internal_default_instance() {
    return reinterpret_cast<const SWelcome*>(
               &_SWelcome_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SWelcome& a, SWelcome& b) {
    a.Swap(&b);
  }
  inline void Swap(SWelcome* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SWelcome* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SWelcome* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SWelcome>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SWelcome& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SWelcome& from) {
    SWelcome::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SWelcome* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "IPC_Protocol.SWelcome";
  }
  protected:
  explicit SWelcome(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEchoMessageFieldNumber = 1,
  };
  // int32 echo_message = 1;
  void clear_echo_message();
  int32_t echo_message() const;
  void set_echo_message(int32_t value);
  private:
  int32_t _internal_echo_message() const;
  void _internal_set_echo_message(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:IPC_Protocol.SWelcome)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t echo_message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_IPCProtocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SWelcome

// int32 echo_message = 1;
inline void SWelcome::clear_echo_message() {
  _impl_.echo_message_ = 0;
}
inline int32_t SWelcome::_internal_echo_message() const {
  return _impl_.echo_message_;
}
inline int32_t SWelcome::echo_message() const {
  // @@protoc_insertion_point(field_get:IPC_Protocol.SWelcome.echo_message)
  return _internal_echo_message();
}
inline void SWelcome::_internal_set_echo_message(int32_t value) {
  
  _impl_.echo_message_ = value;
}
inline void SWelcome::set_echo_message(int32_t value) {
  _internal_set_echo_message(value);
  // @@protoc_insertion_point(field_set:IPC_Protocol.SWelcome.echo_message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace IPC_Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_IPCProtocol_2eproto
